.TH extraordinary_days.dat 5 "2020-04-20" "John Sauter"
.SH NAME
extraordinary_days.dat \- list of days not 86,400 seconds long
.SH synopsis
/usr/share/proleptic_utc_with_leap_seconds/data/extraordinary_days.dat
.SH DESCRIPTION
For software that keeps time according to UTC, measuring the number of
seconds between events on different days requires knowing how long
each day is.  File \fI extraordinary_days.dat \fR provides that
information.
.SH files
/usr/share/proleptic_utc_with_leap_seconds/data/extraordinary_days.dat
.SH notes
The file contains a detailed description of its format.
.SH SEE ALSO
libttime(3)


